[package]
name = "robonomics-runtime-wasm"
version = "0.10.1"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[lib]
name = "robonomics_runtime"
crate-type = ["cdylib"]

[dependencies]
robonomics-runtime = { path = "..", default-features = false }

[features]
default = []
std = [
    "robonomics-runtime/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
